import React, { useState } from 'react';
import { useTravelStore, type PreparationTask } from '../store';
import { CalendarClock, CheckCircle, Circle, Play, Info, Sparkles, Plus, Trash2, Edit2 } from 'lucide-react';

export default function Preparation() {
  const { trips, selectedTripId, generateAutoTasks, updatePreparationTask, deletePreparationTask, addPreparationTask } = useTravelStore();
  const currentTrip = trips.find(t => t.id === selectedTripId);
  
  const [showAddForm, setShowAddForm] = useState(false);
  const [newTaskTitle, setNewTaskTitle] = useState('');
  const [newTaskDate, setNewTaskDate] = useState('');
  const [newTaskNotes, setNewTaskNotes] = useState('');

  const [editingTaskId, setEditingTaskId] = useState<string | null>(null);
  const [editTaskTitle, setEditTaskTitle] = useState('');
  const [editTaskDate, setEditTaskDate] = useState('');
  const [editTaskNotes, setEditTaskNotes] = useState('');

  if (!currentTrip) return <div>旅行を選択してください</div>;

  const tasks = currentTrip.preparationTasks || [];
  
  // ターゲット日でソート (日付が早い順)
  const sortedTasks = [...tasks].sort((a, b) => {
    if (!a.targetDate) return 1;
    if (!b.targetDate) return -1;
    return new Date(a.targetDate).getTime() - new Date(b.targetDate).getTime();
  });

  const isOverdue = (targetDate: string | null, status: string) => {
    if (!targetDate || status === 'completed') return false;
    const target = new Date(targetDate);
    target.setHours(0, 0, 0, 0);
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    return target < today;
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'completed': return <CheckCircle className="text-emerald-500" size={24} />;
      case 'in_progress': return <Play className="text-amber-500" size={24} />;
      default: return <Circle className="text-slate-300" size={24} />;
    }
  };

  const getStatusText = (status: string) => {
    switch (status) {
      case 'completed': return '完了';
      case 'in_progress': return '手配中';
      default: return '未着手';
    }
  };

  const handleStatusToggle = (task: PreparationTask) => {
    const nextStatus = 
      task.status === 'pending' ? 'in_progress' : 
      task.status === 'in_progress' ? 'completed' : 'pending';
    updatePreparationTask(task.id, { status: nextStatus });
  };

  const handleAddTask = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTaskTitle.trim()) return;
    
    addPreparationTask({
      title: newTaskTitle,
      category: 'その他',
      targetDate: newTaskDate || null,
      status: 'pending',
      notes: newTaskNotes,
      isAutoGenerated: false
    });
    setNewTaskTitle('');
    setNewTaskDate('');
    setNewTaskNotes('');
    setShowAddForm(false);
  };

  const startEditing = (task: PreparationTask) => {
    setEditingTaskId(task.id);
    setEditTaskTitle(task.title);
    setEditTaskDate(task.targetDate || '');
    setEditTaskNotes(task.notes || '');
  };

  const handleUpdateTask = (e: React.FormEvent, taskId: string) => {
    e.preventDefault();
    if (!editTaskTitle.trim()) return;
    updatePreparationTask(taskId, {
      title: editTaskTitle,
      targetDate: editTaskDate || null,
      notes: editTaskNotes
    });
    setEditingTaskId(null);
  };

  return (
    <div className="space-y-6 pb-20">
      <div className="flex items-center justify-between">
        <h2 className="text-xl font-bold flex items-center gap-2">
          <CalendarClock className="text-indigo-500" />
          準備・予約タスク
        </h2>
        <button 
          onClick={generateAutoTasks}
          className="flex items-center gap-1 bg-indigo-100 text-indigo-700 px-3 py-1.5 rounded-full text-sm font-bold shadow-sm"
        >
          <Sparkles size={16} />
          自動スケジュール生成
        </button>
      </div>

      <div className="glass-panel p-4 mb-6">
        <div className="flex gap-3 items-start text-sm text-slate-600">
          <Info className="text-indigo-400 shrink-0 mt-0.5" size={18} />
          <p>
            「自動スケジュール生成」を押すと、旅行日（{currentTrip.tripDate ? new Date(currentTrip.tripDate).toLocaleDateString() : '未定'}）から逆算して、飛行機やホテルの予約開始目安日を自動でタスクリストに追加します。
          </p>
        </div>
      </div>

      <div className="space-y-3">
        {sortedTasks.length === 0 ? (
          <div className="text-center py-10 text-slate-400">
            <CalendarClock size={48} className="mx-auto mb-3 opacity-20" />
            <p>タスクがありません。</p>
            <p className="text-sm mt-1">「自動スケジュール生成」で標準項目を追加できます。</p>
          </div>
        ) : (
          sortedTasks.map(task => {
            const overdue = isOverdue(task.targetDate, task.status);
            return (
            <div key={task.id} className={`glass-panel p-4 flex gap-4 items-start ${overdue ? 'border-2 border-rose-200 bg-rose-50/30' : ''}`}>
              <button 
                onClick={() => handleStatusToggle(task)}
                className="mt-1 shrink-0 transition-transform active:scale-90"
              >
                {getStatusIcon(task.status)}
              </button>
              
              <div className="flex-1 min-w-0">
                {editingTaskId === task.id ? (
                  <form onSubmit={(e) => handleUpdateTask(e, task.id)} className="space-y-3">
                    <div>
                      <div className="text-xs font-bold text-slate-700 mb-1">やること（必須）</div>
                      <input type="text" className="input-field" style={{ marginBottom: 0 }} value={editTaskTitle} onChange={e => setEditTaskTitle(e.target.value)} required />
                    </div>
                    <div>
                      <div className="text-xs font-bold text-slate-700 mb-1">目標日・期限（任意）</div>
                      <input type="date" className="input-field" style={{ marginBottom: 0 }} value={editTaskDate} onChange={e => setEditTaskDate(e.target.value)} />
                    </div>
                    <div>
                      <div className="text-xs font-bold text-slate-700 mb-1">メモ・詳細（任意）</div>
                      <textarea className="input-field" style={{ marginBottom: 0, minHeight: '60px' }} value={editTaskNotes} onChange={e => setEditTaskNotes(e.target.value)} />
                    </div>
                    <div className="flex gap-2 mt-2">
                      <button type="submit" className="btn-primary flex-1 py-2 text-sm">保存</button>
                      <button type="button" className="btn-secondary py-2 text-sm" onClick={() => setEditingTaskId(null)}>キャンセル</button>
                    </div>
                  </form>
                ) : (
                  <>
                    <div className="flex items-start justify-between gap-2">
                      <h3 className={`font-bold ${task.status === 'completed' ? 'text-slate-400 line-through' : 'text-slate-800'}`}>
                        {task.title}
                      </h3>
                      <div className="flex gap-1 shrink-0">
                        <button onClick={() => startEditing(task)} className="text-slate-300 hover:text-indigo-400 p-1">
                          <Edit2 size={16} />
                        </button>
                        <button onClick={() => deletePreparationTask(task.id)} className="text-slate-300 hover:text-rose-400 p-1">
                          <Trash2 size={16} />
                        </button>
                      </div>
                    </div>
                    
                    <div className="flex items-center gap-2 mt-1">
                      <span className={`text-xs px-2 py-0.5 rounded-full font-medium
                        ${task.status === 'completed' ? 'bg-emerald-100 text-emerald-700' :
                          task.status === 'in_progress' ? 'bg-amber-100 text-amber-700' :
                          'bg-slate-100 text-slate-600'}`}>
                        {getStatusText(task.status)}
                      </span>
                      
                      {task.targetDate && (
                        <span className={`text-xs font-medium px-2 py-0.5 rounded ${overdue ? 'bg-rose-100 text-rose-700' : 'bg-indigo-50 text-indigo-600'}`}>
                          {overdue ? '⚠️ 期限切れ: ' : '目安: '}
                          {new Date(task.targetDate).toLocaleDateString()}
                        </span>
                      )}
                    </div>
                    
                    {task.notes && (
                      <p className="text-xs text-slate-500 mt-2 bg-slate-50 p-2 rounded whitespace-pre-wrap">
                        {task.notes}
                      </p>
                    )}
                  </>
                )}
              </div>
            </div>
          )})
        )}
      </div>

      {showAddForm ? (
        <form onSubmit={handleAddTask} className="glass-panel p-4 space-y-3">
          <div className="border-b border-slate-200 pb-2 mb-3">
            <h3 className="font-bold text-slate-800">新しいタスクを追加</h3>
          </div>
          <div>
            <div className="text-sm font-bold text-slate-700 mb-1">やること（必須）</div>
            <input
              type="text"
              placeholder="例: レンタカーの予約"
              className="input-field"
              style={{ marginBottom: 0 }}
              value={newTaskTitle}
              onChange={e => setNewTaskTitle(e.target.value)}
              required
              autoFocus
            />
          </div>
          <div>
            <div className="text-sm font-bold text-slate-700 mb-1">目標日・期限（任意）</div>
            <input
              type="date"
              className="input-field"
              style={{ marginBottom: 0 }}
              value={newTaskDate}
              onChange={e => setNewTaskDate(e.target.value)}
            />
          </div>
          <div>
            <div className="text-sm font-bold text-slate-700 mb-1">メモ・詳細（任意）</div>
            <textarea
              placeholder="例: ファミリーカーを3日間借りる"
              className="input-field"
              style={{ marginBottom: 0, minHeight: '60px' }}
              value={newTaskNotes}
              onChange={e => setNewTaskNotes(e.target.value)}
            />
          </div>
          <div className="flex gap-2 pt-2">
            <button type="submit" className="btn-primary flex-1">
              追加する
            </button>
            <button type="button" onClick={() => setShowAddForm(false)} className="btn-secondary flex-1">
              キャンセル
            </button>
          </div>
        </form>
      ) : (
        <button 
          onClick={() => setShowAddForm(true)}
          className="w-full glass-panel p-4 flex items-center justify-center gap-2 text-indigo-600 font-bold"
        >
          <Plus size={20} />
          カスタムタスクを追加
        </button>
      )}
    </div>
  );
}
