import React, { useState } from 'react';
import { useTravelStore, type PreparationTask } from '../store';
import { CalendarClock, CheckCircle, Circle, Play, Info, Sparkles, Plus, Trash2 } from 'lucide-react';

export default function Preparation() {
  const { trips, selectedTripId, generateAutoTasks, updatePreparationTask, deletePreparationTask, addPreparationTask } = useTravelStore();
  const currentTrip = trips.find(t => t.id === selectedTripId);
  const [showAddForm, setShowAddForm] = useState(false);
  const [newTaskTitle, setNewTaskTitle] = useState('');
  const [newTaskDate, setNewTaskDate] = useState('');

  if (!currentTrip) return <div>旅行を選択してください</div>;

  const tasks = currentTrip.preparationTasks || [];
  
  // ターゲット日でソート (日付が早い順)
  const sortedTasks = [...tasks].sort((a, b) => {
    if (!a.targetDate) return 1;
    if (!b.targetDate) return -1;
    return new Date(a.targetDate).getTime() - new Date(b.targetDate).getTime();
  });

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'completed': return <CheckCircle className="text-emerald-500" size={24} />;
      case 'in_progress': return <Play className="text-amber-500" size={24} />;
      default: return <Circle className="text-slate-300" size={24} />;
    }
  };

  const getStatusText = (status: string) => {
    switch (status) {
      case 'completed': return '完了';
      case 'in_progress': return '手配中';
      default: return '未着手';
    }
  };

  const handleStatusToggle = (task: PreparationTask) => {
    const nextStatus = 
      task.status === 'pending' ? 'in_progress' : 
      task.status === 'in_progress' ? 'completed' : 'pending';
    updatePreparationTask(task.id, { status: nextStatus });
  };

  const handleAddTask = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTaskTitle.trim()) return;
    
    addPreparationTask({
      title: newTaskTitle,
      category: 'その他',
      targetDate: newTaskDate || null,
      status: 'pending',
      notes: '',
      isAutoGenerated: false
    });
    setNewTaskTitle('');
    setNewTaskDate('');
    setShowAddForm(false);
  };

  return (
    <div className="space-y-6 pb-20">
      <div className="flex items-center justify-between">
        <h2 className="text-xl font-bold flex items-center gap-2">
          <CalendarClock className="text-indigo-500" />
          準備・予約タスク
        </h2>
        <button 
          onClick={generateAutoTasks}
          className="flex items-center gap-1 bg-indigo-100 text-indigo-700 px-3 py-1.5 rounded-full text-sm font-bold shadow-sm"
        >
          <Sparkles size={16} />
          自動スケジュール生成
        </button>
      </div>

      <div className="glass-panel p-4 mb-6">
        <div className="flex gap-3 items-start text-sm text-slate-600">
          <Info className="text-indigo-400 shrink-0 mt-0.5" size={18} />
          <p>
            「自動スケジュール生成」を押すと、旅行日（{currentTrip.tripDate ? new Date(currentTrip.tripDate).toLocaleDateString() : '未定'}）から逆算して、飛行機やホテルの予約開始目安日を自動でタスクリストに追加します。
          </p>
        </div>
      </div>

      <div className="space-y-3">
        {sortedTasks.length === 0 ? (
          <div className="text-center py-10 text-slate-400">
            <CalendarClock size={48} className="mx-auto mb-3 opacity-20" />
            <p>タスクがありません。</p>
            <p className="text-sm mt-1">「自動スケジュール生成」で標準項目を追加できます。</p>
          </div>
        ) : (
          sortedTasks.map(task => (
            <div key={task.id} className="glass-panel p-4 flex gap-4 items-start">
              <button 
                onClick={() => handleStatusToggle(task)}
                className="mt-1 shrink-0 transition-transform active:scale-90"
              >
                {getStatusIcon(task.status)}
              </button>
              
              <div className="flex-1 min-w-0">
                <div className="flex items-start justify-between gap-2">
                  <h3 className={`font-bold ${task.status === 'completed' ? 'text-slate-400 line-through' : 'text-slate-800'}`}>
                    {task.title}
                  </h3>
                  <button 
                    onClick={() => deletePreparationTask(task.id)}
                    className="text-slate-300 hover:text-rose-400"
                  >
                    <Trash2 size={16} />
                  </button>
                </div>
                
                <div className="flex items-center gap-2 mt-1">
                  <span className={`text-xs px-2 py-0.5 rounded-full font-medium
                    ${task.status === 'completed' ? 'bg-emerald-100 text-emerald-700' :
                      task.status === 'in_progress' ? 'bg-amber-100 text-amber-700' :
                      'bg-slate-100 text-slate-600'}`}>
                    {getStatusText(task.status)}
                  </span>
                  
                  {task.targetDate && (
                    <span className="text-xs font-medium text-indigo-600 bg-indigo-50 px-2 py-0.5 rounded">
                      目安: {new Date(task.targetDate).toLocaleDateString()}
                    </span>
                  )}
                </div>
                
                {task.notes && (
                  <p className="text-xs text-slate-500 mt-2 bg-slate-50 p-2 rounded">
                    {task.notes}
                  </p>
                )}
              </div>
            </div>
          ))
        )}
      </div>

      {showAddForm ? (
        <form onSubmit={handleAddTask} className="glass-panel p-4 space-y-3">
          <input
            type="text"
            placeholder="タスク名 (例: レンタカー予約)"
            className="input-field"
            value={newTaskTitle}
            onChange={e => setNewTaskTitle(e.target.value)}
            autoFocus
          />
          <input
            type="date"
            className="input-field"
            value={newTaskDate}
            onChange={e => setNewTaskDate(e.target.value)}
          />
          <div className="flex gap-2">
            <button type="button" onClick={() => setShowAddForm(false)} className="btn-secondary flex-1">
              キャンセル
            </button>
            <button type="submit" className="btn-primary flex-1">
              追加
            </button>
          </div>
        </form>
      ) : (
        <button 
          onClick={() => setShowAddForm(true)}
          className="w-full glass-panel p-4 flex items-center justify-center gap-2 text-indigo-600 font-bold"
        >
          <Plus size={20} />
          カスタムタスクを追加
        </button>
      )}
    </div>
  );
}
